*Readme needs to be updated after development.*

* Overview
:PROPERTIES:
:HASH:     1516310490598954255
:UPDATED:  <2022-12-18 Sun 01:20>
:END:

This simple plugin has 2 primary functions:

* Sending of tasks to your Inbox in Ticktick
:PROPERTIES:
:HASH:     1169345933550181700
:UPDATED:  <2022-12-18 Sun 01:20>
:END:

This function allows you to quickly send a task to your Inbox in Ticktick.

**Sending a task with priority**

By including a block attribute when composing your task, you are able to send a task to ticktick with priority.

#+begin_src
Do this task
priority:: 4
#+end_src

_Optional: You can also specify the project that you want all tasks to be sent to, and label that you want attached to these tasks._

# Pulling in of tasks

**Pulling tasks from specific projects**

This function pulls the active tasks (and their sub-tasks as separate, child-blocks) from a selected Project of your choice (as indicated in your settings file). I created this plugin as my workflow includes using Ticktick as a Quick Capture tool, and Logseq as my main todo manager. As a result, once the tasks are captured in Logseq, they are removed from Ticktick. If the task or sub-task contains a description, it will be included as well. This plugin can be used on all pages except the home page.

I've included a functionality where you can either:

1. Have `TODO` added to the task when you import them into Logseq.

or

2. Include them in Ticktick itself before you import them. This gives you the flexibility of adding other attributes such as NOW, WAITING, etc. on Ticktick, or even setting it as a Logseq page before it gets imported.

or

3. Both.

**Pulling tasks that are due TODAY, regardless of projects**

Instead of pulling tasks from specific projects, you can pull tasks that are due TODAY, by using the command `/pull today`.

**Scheduled Tasks**
